name: code analysis & formatting

on: [push, pull_request]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v2
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
      - name: Initialize workspace through melos
        run: melos boostrap
      - name: Linter
        run: melos analyze
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v2
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
      - name: Initialize workspace through melos
        run: melos boostrap
      - name: Format
        run: melos format --output none --set-exit-if-changed
        working-directory: ./flutter_secure_storage
