name: integration test
on: [pull_request]
jobs:
  drive_android:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
        - name: Install melos
          run: |
            flutter pub global activate melos
            echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
            echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
        - name: Initialize workspace through melos
          run: melos boostrap
        - name: "Run Flutter Driver tests API 18"
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 18
            target: default
            arch: x86
            script: "cd example && flutter drive --target=test_driver/app.dart"
            working-directory: ./flutter_secure_storage
        - name: "Run Flutter Driver tests API 33"
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 33
            target: google_apis
            arch: x86_64
            script: "cd example && flutter drive --target=test_driver/app.dart"
            working-directory: ./flutter_secure_storage
